#ifndef KEVCC_TOKENIZER_GENERATOR_INCLUDE_FINITE_AUTOMATON_OBJECT_POOL_INTLISTMAP_NODE_POOL_H
#define KEVCC_TOKENIZER_GENERATOR_INCLUDE_FINITE_AUTOMATON_OBJECT_POOL_INTLISTMAP_NODE_POOL_H
#include "tokenizer_generator/include/finite_automaton/hashmap/intlist_map.h"

KevIntListMapNode* kev_intlistmap_node_pool_acquire(void);
KevIntListMapNode* kev_intlistmap_node_pool_allocate(void);
void kev_intlistmap_node_pool_deallocate(KevIntListMapNode* intlistmap_node);
void kev_intlistmap_node_pool_free(void);

#endif
