#ifndef KEVCC_TOKENIZER_GENERATOR_INCLUDE_FINITE_AUTOMATON_OBJECT_POOL_SET_CROSS_LIST_NODE_POOL_H
#define KEVCC_TOKENIZER_GENERATOR_INCLUDE_FINITE_AUTOMATON_OBJECT_POOL_SET_CROSS_LIST_NODE_POOL_H

#include "tokenizer_generator/include/finite_automaton/list/set_cross_list.h"


KevSetCrossListNode* kev_set_cross_list_node_pool_acquire(void);
KevSetCrossListNode* kev_set_cross_list_node_pool_allocate(void);
void kev_set_cross_list_node_pool_deallocate(KevSetCrossListNode* node);
void kev_set_cross_list_node_pool_free(void);


#endif
