#ifndef _KLANG_INCLUDE_LANG_KLCONFIG_H_
#define _KLANG_INCLUDE_LANG_KLCONFIG_H_

#if defined (__GNUC__) || defined (__clang__)
#define KLCONFIG_USE_JMPTABLE
#endif


#define klconfig_library_foreach(macro) \
  macro(RTCPL)                          \
  macro(RTCPL_WRAPPER)                  \
  macro(TRACEBACK)                      \
  macro(BASIC)                          \
  macro(PRINT)                          \
  macro(STREAM)                         \
  macro(STRING)                         \
  macro(CAST)                           \
  macro(OS)                             \
  macro(GC)



#define KLCONFIG_LIBRARY_RTCPL_LIBNAME_QUOTE          "runtime_compiler.so"
#define KLCONFIG_LIBRARY_RTCPL_WRAPPER_LIBNAME_QUOTE  "rtcpl_wrapper.so"
#define KLCONFIG_LIBRARY_TRACEBACK_LIBNAME_QUOTE      "traceback.so"
#define KLCONFIG_LIBRARY_BASIC_LIBNAME_QUOTE          "basic.so"
#define KLCONFIG_LIBRARY_PRINT_LIBNAME_QUOTE          "print.so"
#define KLCONFIG_LIBRARY_STREAM_LIBNAME_QUOTE         "stream.so"
#define KLCONFIG_LIBRARY_STRING_LIBNAME_QUOTE         "string.so"
#define KLCONFIG_LIBRARY_CAST_LIBNAME_QUOTE           "cast.so"
#define KLCONFIG_LIBRARY_OS_LIBNAME_QUOTE             "os.so"
#define KLCONFIG_LIBRARY_GC_LIBNAME_QUOTE             "gc.so"

#define KLCONFIG_LIBRARY_RTCPL_ENTRYFUNCNAME          kllib_rtcpl_init
#define KLCONFIG_LIBRARY_RTCPL_WRAPPER_ENTRYFUNCNAME  kllib_rtcpl_wrapper_init
#define KLCONFIG_LIBRARY_TRACEBACK_ENTRYFUNCNAME      kllib_traceback_init
#define KLCONFIG_LIBRARY_BASIC_ENTRYFUNCNAME          kllib_basic_init
#define KLCONFIG_LIBRARY_PRINT_ENTRYFUNCNAME          kllib_print_init
#define KLCONFIG_LIBRARY_STREAM_ENTRYFUNCNAME         kllib_stream_init
#define KLCONFIG_LIBRARY_STRING_ENTRYFUNCNAME         kllib_string_init
#define KLCONFIG_LIBRARY_CAST_ENTRYFUNCNAME           kllib_cast_init
#define KLCONFIG_LIBRARY_OS_ENTRYFUNCNAME             kllib_os_init
#define KLCONFIG_LIBRARY_GC_ENTRYFUNCNAME             kllib_gc_init

#define KLCONFIG_TOSTRING_RAW(s)  #s
#define KLCONFIG_TOSTRING(s)      KLCONFIG_TOSTRING_RAW(s)

#define KLCONFIG_LIBRARY_RTCPL_ENTRYFUNCNAME_QUOTE          KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_RTCPL_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_RTCPL_WRAPPER_ENTRYFUNCNAME_QUOTE  KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_RTCPL_WRAPPER_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_TRACEBACK_ENTRYFUNCNAME_QUOTE      KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_TRACEBACK_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_BASIC_ENTRYFUNCNAME_QUOTE          KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_BASIC_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_PRINT_ENTRYFUNCNAME_QUOTE          KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_PRINT_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_STREAM_ENTRYFUNCNAME_QUOTE         KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_STREAM_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_STRING_ENTRYFUNCNAME_QUOTE         KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_STRING_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_CAST_ENTRYFUNCNAME_QUOTE           KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_CAST_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_OS_ENTRYFUNCNAME_QUOTE             KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_OS_ENTRYFUNCNAME)
#define KLCONFIG_LIBRARY_GC_ENTRYFUNCNAME_QUOTE             KLCONFIG_TOSTRING(KLCONFIG_LIBRARY_GC_ENTRYFUNCNAME)


#endif

