INC_DIR = $(PARGEN_DIR)include/
SRC_DIR = $(PARGEN_DIR)src/
BIN_DIR = $(PARGEN_DIR)bin/
LIB_DIR = $(PARGEN_DIR)lib/

#lr directory
LR_DIR = $(SRC_DIR)lr/

all :
	mkdir -p $(BIN_DIR)
	$(MAKE) -C $(LR_DIR)


.PHONY: clean
clean :
	rm $(BIN_DIR)*
